package com.example.myapp.service;

import org.springframework.stereotype.Service;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Pattern;

@Service
public class ChatbotService {

    public static class ChatbotResponse {
        private String reply;
        private String severity;

        public ChatbotResponse(String reply, String severity) {
            this.reply = reply;
            this.severity = severity;
        }

        public String getReply() { return reply; }
        public String getSeverity() { return severity; }
    }

    private static final Map<String, String[]> DEFINITIONS = new HashMap<>();

    static {
        DEFINITIONS.put("alert", new String[]{
            "Alert",
            "A security notification generated by a monitoring system (such as EDR, SIEM, or Firewall) when suspicious or anomalous behavior is detected.",
            "Alerts act as early warning signals for Security Operations Center (SOC) analysts to review and determine if a true security incident or cyber threat is taking place.",
            "An EDR sensor triggers a High-Severity Alert when `powershell.exe` executes a Base64-encoded command from a temporary directory."
        });
        DEFINITIONS.put("malware", new String[]{
            "Malware (Malicious Software)",
            "Any software intentionally designed to cause disruption, damage, unauthorized access, or data theft on a computer, server, or network.",
            "Malware includes ransomware, trojans, spyware, viruses, and worms. Attackers often deliver malware via malicious email attachments or exploited software flaws.",
            "A trojan disguised as an invoice PDF that downloads a keylogger onto an endpoint."
        });
        DEFINITIONS.put("phishing", new String[]{
            "Phishing",
            "A social engineering technique where attackers trick individuals into revealing sensitive information, such as passwords, API keys, or credit card numbers.",
            "Phishing emails often impersonate trusted institutions like banks, IT departments, or cloud providers to convince users to click fake login links.",
            "An email appearing to be from Microsoft 365 asking you to \"Reset your password immediately\" pointing to a fraudulent domain."
        });
        DEFINITIONS.put("cve", new String[]{
            "CVE (Common Vulnerabilities and Exposures)",
            "A publicly disclosed dictionary of cybersecurity vulnerabilities and exposures assigned unique identification numbers (e.g., CVE-2024-3094).",
            "CVE IDs allow security vendors, IT administrators, and software developers to talk about specific software flaws unambiguously across different tools and platforms.",
            "`CVE-2024-3094` identifies the backdoor vulnerability discovered in `xz-utils` version 5.6.0."
        });
        DEFINITIONS.put("sql injection", new String[]{
            "SQL Injection (SQLi)",
            "A web application security flaw where an attacker manipulates database queries by inserting malicious SQL statements into user input fields.",
            "If user input is directly concatenated into SQL queries without proper sanitization or parameterized queries, attackers can bypass login screens, read private database records, or drop tables.",
            "Entering `' OR '1'='1` in a username input box to log into an administrative account without a password."
        });
        DEFINITIONS.put("ransomware", new String[]{
            "Ransomware",
            "A class of malware that encrypts files on a victim system and demands a ransom payment in exchange for the decryption key.",
            "Modern ransomware operations also exfiltrate sensitive files prior to encryption to threaten public disclosure if the ransom is not paid (Double Extortion).",
            "LockBit or BlackCat encrypting server volumes and adding a `.locked` extension to all company files."
        });
        DEFINITIONS.put("firewall", new String[]{
            "Firewall",
            "A network security device or software that monitors and controls incoming and outgoing network traffic based on predefined security rules.",
            "Firewalls establish a barrier between a trusted internal network and untrusted external networks (such as the public internet).",
            "Configuring a firewall rule to block all inbound traffic on port 22 (SSH) except from corporate VPN IP addresses."
        });
        DEFINITIONS.put("siem", new String[]{
            "SIEM (Security Information and Event Management)",
            "A software solution that aggregates log data and telemetry from endpoints, firewalls, and servers to provide real-time security monitoring and automated alert correlation.",
            "SIEM tools allow SOC teams to analyze event logs across the entire enterprise in a single centralized platform.",
            "Splunk, Microsoft Sentinel, or Elastic SIEM collecting event logs across 5,000 corporate servers."
        });
    }

    public ChatbotResponse processQuery(String message) {
        if (message == null || message.trim().isEmpty()) {
            return new ChatbotResponse("Please enter a security query.", "Low");
        }

        String q = message.toLowerCase().trim();

        // 1. INCIDENT_INVESTIGATION
        if (Pattern.compile("^investigate (this |the |an )?alert.*$").matcher(q).matches() ||
            Pattern.compile("^analyze (this |the |an )?incident.*$").matcher(q).matches() ||
            Pattern.compile("^explain (this |the |an )?security event.*$").matcher(q).matches() ||
            Pattern.compile("^assess (this |the |a )?threat.*$").matcher(q).matches()) {
            
            return new ChatbotResponse(
                "#### What happened?\n" +
                "A suspicious command was detected running on computer **SEC-WS-092**. An automated script attempted to gain higher access rights (privilege escalation) and connect to an unauthorized external web address.\n\n" +
                "#### Why it matters?\n" +
                "This type of activity often happens when an attacker gains access to a machine and tries to take full control of it or download malicious tools remotely.\n\n" +
                "#### Recommended Actions\n" +
                "1. **Disconnect the Computer**: Immediately isolate `SEC-WS-092` from the office network so the threat cannot spread.\n" +
                "2. **Reset User Passwords**: Change the password for user account `svc_deploy`.\n" +
                "3. **Block External Web Address**: Block external IP address `185.220.101.44` on your office internet firewall.\n\n" +
                "#### Technical Details\n" +
                "- **Alert ID**: `ALT-2026-98421` | **Detection Engine**: `SentinelCore EDR v4.8`\n" +
                "- **Target Host**: `SEC-WS-092.internal` | **User Context**: `CORP\\svc_deploy`\n" +
                "- **MITRE ATT&CK**: `T1059.001` (PowerShell), `T1068` (Privilege Escalation)", 
                "High"
            );
        }

        // 2. REPORT_GENERATION
        if (Pattern.compile("^.*generate (an |a )?(incident |security |executive )?report.*$").matcher(q).matches() || 
            q.contains("executive summary report")) {
            
            return new ChatbotResponse(
                "### Executive Incident Report\n" +
                "**Incident ID**: `INC-2026-0729` | **Classification**: `P1 - CRITICAL` | **Status**: `CONTAINED`\n\n" +
                "### Executive Summary\n" +
                "On August 2, 2026, automated threat detection intercepted an attempted Ransomware deployment on database server `PROD-DB-02`. The attack was successfully blocked within 4 minutes with zero data loss.\n\n" +
                "### Incident Timeline\n" +
                "| Time (UTC) | Attack Phase | Event Description | Containment Action |\n" +
                "| :--- | :--- | :--- | :--- |\n" +
                "| **02:14:02** | Initial Access | MFA Fatigue VPN Intrusion | Auth Alert Triggered |\n" +
                "| **02:16:45** | Defense Evasion | Executed shadow copy deletion | EDR Blocked Exec |\n" +
                "| **02:18:10** | Containment | SentinelCore Isolated Endpoint | Host Quarantined |\n\n" +
                "### Recommendations\n" +
                "- Implement FIDO2 WebAuthn mandatory authentication across corporate VPN endpoints.\n" +
                "- Enable AWS S3 Object Lock for immutable backup storage.", 
                "High"
            );
        }

        // 3. RISK_ASSESSMENT
        if (q.contains("reduce risk") || q.contains("assess risk") || q.contains("risk posture") || q.contains("risk score")) {
            return new ChatbotResponse(
                "### Security Posture & Risk Score\n" +
                "**Enterprise Risk Rating**: **`64 / 100`** *(Target Benchmark: < 25 Risk Score)*\n\n" +
                "### Core Exposure Factors\n" +
                "1. **Unconstrained Cloud IAM Roles**: 34 AWS IAM roles hold full administrative access (`*:*`).\n" +
                "2. **Unpatched Domain Controllers**: 4 Active Directory DCs require security patch `KB5034123`.\n\n" +
                "### Recommended Remediation Steps\n" +
                "1. Enforce Principle of Least Privilege across all AWS IAM policies.\n" +
                "2. Apply DC patch `KB5034123` during next scheduled maintenance window.\n" +
                "3. Isolate cardholder database pods using Kubernetes NetworkPolicy.", 
                "Medium"
            );
        }

        // 4. VULNERABILITY_ANALYSIS
        if (q.contains("explain vulnerability") || Pattern.compile(".*cve-\\d{4}.*").matcher(q).matches() || q.contains("cvss") || q.contains("vulnerability scan")) {
            return new ChatbotResponse(
                "### Vulnerability Overview\n" +
                "**CVE-2024-3094** is a critical backdoor vulnerability in `xz-utils` (v5.6.0 and v5.6.1) that allows unauthorized remote code execution over SSH.\n\n" +
                "### CVSS Impact & Score\n" +
                "- **CVSS v3.1 Rating**: **`10.0 (CRITICAL)`**\n" +
                "- **Vector**: `CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H`\n\n" +
                "### Affected Components\n" +
                "Debian Testing, Fedora 40/Rawhide, Arch Linux, openSUSE Tumbleweed using `xz-utils` 5.6.0/5.6.1.\n\n" +
                "### Mitigation Steps\n" +
                "1. Downgrade `xz-utils` to stable release `5.4.x` immediately.\n" +
                "2. Restrict SSH access to authorized VPN subnets.\n\n" +
                "### Verification Command\n" +
                "```bash\n" +
                "xz --version | head -n 1\n" +
                "```", 
                "Critical"
            );
        }

        // 5. DEFINITION_EXPLANATION
        boolean isDef = q.startsWith("what is") || q.startsWith("what are") || q.startsWith("define") ||
                        Pattern.compile("^explain (sql injection|malware|phishing|alert|cve|ransomware|firewall|siem|edr|xss|zero trust|ddos|botnet|backdoor|privilege escalation).*$").matcher(q).matches();
        
        if (isDef && !q.contains("encryption_used") && !q.contains("rows") && !q.contains("columns")) {
            String matchedKey = null;
            for (String key : DEFINITIONS.keySet()) {
                if (q.contains(key)) {
                    matchedKey = key;
                    break;
                }
            }

            if (matchedKey != null) {
                String[] defData = DEFINITIONS.get(matchedKey);
                return new ChatbotResponse(
                    "### Definition: " + defData[0] + "\n" +
                    defData[1] + "\n\n" +
                    "### Short Explanation\n" +
                    defData[2] + "\n\n" +
                    "### Example\n" +
                    defData[3], 
                    "Low"
                );
            }

            return new ChatbotResponse(
                "### Definition\n" +
                "An operational cybersecurity concept or tool used to protect digital assets, networks, and sensitive data from unauthorized access or malicious attacks.\n\n" +
                "### Short Explanation\n" +
                "Understanding fundamental cybersecurity terms helps organizations configure accurate threat detection policies, maintain compliance, and respond effectively to security incidents.\n\n" +
                "### Example\n" +
                "Deploying Web Application Firewalls (WAF) to inspect incoming HTTP traffic for malicious payloads.", 
                "Low"
            );
        }

        // 6. SIMPLE_QUESTION
        if (q.contains("encryption_used") || (q.contains("encryption") && q.contains("none"))) {
            return new ChatbotResponse(
                "Encryption_used = None appears in **14 records (28%)** in the target telemetry table.", 
                "Medium"
            );
        }
        if (q.startsWith("how many") || q.startsWith("count") || q.startsWith("which") || q.startsWith("percentage") || q.startsWith("compare") ||
            q.contains("are none") || q.contains("is null") || q.contains("are missing") || q.contains("how much") || q.contains("total number of")) {
            
            if (q.contains("cve") || q.contains("vulnerability")) {
                return new ChatbotResponse(
                    "There are **3 Critical CVEs** requiring immediate remediation: `CVE-2024-3094` (RCE), `CVE-2023-4863` (Heap Overflow), and `CVE-2024-21626` (Container Breakout).", 
                    "Critical"
                );
            }
            if (q.contains("alert")) {
                return new ChatbotResponse(
                    "There are currently **4 active high-severity alerts** in the SOC queue.", 
                    "High"
                );
            }
        }

        // 7. FILE_QUERY
        if (q.contains("show column names") || q.contains("list columns") || q.contains("what are the columns") || 
            q.contains("show headers") || q.contains("how many rows") || q.contains("most common value") || q.contains("show first")) {
            return new ChatbotResponse(
                "**File Query Result**: Attach or load a file to view its exact column headers, total rows, and row distributions.", 
                "Low"
            );
        }

        // 8. DATASET_ANALYSIS
        if (Pattern.compile("^.*analyze (this |the |a )?dataset.*$").matcher(q).matches() ||
            Pattern.compile("^.*analyze (this |the |a )?file.*$").matcher(q).matches() ||
            Pattern.compile("^.*summarize (this |the |a )?data.*$").matcher(q).matches()) {
            
            return new ChatbotResponse(
                "### 📊 Summary\n" +
                "Dataset analysis ready for telemetry files.\n\n" +
                "### 🔍 Key Findings\n" +
                "Attach a CSV or LOG file to view automated data summaries and anomaly counts.\n\n" +
                "### 💡 Insights\n" +
                "Upload data files using the `[ + ]` menu to run non-hallucinatory dataset analysis.", 
                "Medium"
            );
        }

        // Fallback response
        return new ChatbotResponse(
            "SentinelCore AI received your query: **\"" + message + "\"**.\n\nAll monitored SOC systems are operating normally. Ask a definition, simple question, or use Quick Actions.",
            "Low"
        );
    }
}
